package com.pesse.sms.common;

public enum ConfigKeys {
	SERVER_CONTEXT,
	JDBC_URL,
	SUPER_USER,
	ACTIVATION_KEY_GEN,
	JQUERY_URL,
	INSTITUTE_PASSWORD,
	GATEWAY_USERID,
	GATEWAY_PASSWORD, 
	JQUERYUI_URL,
}